name: Simple GitHub Pages Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          mkdir _site
          cp index.html _site/index.html
          cp -r frontend/css _site/
          cp -r frontend/js _site/
          cp -r frontend/images _site/ || true
          cp -r frontend/icons _site/ || true
          cp frontend/manifest.json _site/
          cp frontend/sw.js.disabled _site/
          # Add any other needed assets here

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy
        uses: actions/deploy-pages@v4
